### ISSUE TITLE
Render main map

### ISSUE THREAD

**Issue by nglgzz** [learn-anything/old#82]
The main map doesn't have a root node like all other maps, it has all nodes at the same level, so it can't be rendered properly with the new system.

How do we render it?

Any ideas are welcome.

**Comment by nikitavoloboev** [comment]
Can we tweak `la-map` component only for that specific case? To render all nodes as stand alone?

**Comment by nglgzz** [comment]
That's actually a good idea, when I'm done integrating la-map into the main repo I'll take a look at this.
